# Change these first
owner: imedicalservices # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:
  - name: AXA
    url: https://axacolpatria.imedicalcloud.net/api/v1/healthz?token=3a9174fb-6e18-41c7-a53d-6d1ddf871819

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /statuspage
  logoUrl: https://avatars.githubusercontent.com/u/107059814
  name: iMedical Estado de Servicios
  introTitle: "**iMedical** plataforma de servicios de salud."
  introMessage: Esta p치gina muestra en **tiempo real** el estado de los servicios de iMedical.
  navbar:
    - title: Estado
      href: /statuspage
    - title: M치s informaci칩n
      href: https://www.imedicalservices.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  URL: "URL"
  estado: "Estado"
  historia: "Historia"
  tiempo de actividad: "Tiempo de actividad"
  arriba: "游릴 Arriba"
  degradado: "游릳 Degradado"
  abajo: "游린 Abajo"
  responseTimeGraphAlt: "Gr치fico de tiempo de respuesta"
  ms: "ms"
  responseTime: "Tiempo de respuesta"
  responseTimeDay: "Tiempo de respuesta 24 horas"
  responseTimeWeek: "Tiempo de respuesta 7 d칤as"
  responseTimeMonth: "Tiempo de respuesta 30 d칤as"
  responseTimeYear: "Tiempo de respuesta 1 a침o"
  uptime: "Tiempo de actividad total"
  uptimeDay: "tiempo de actividad 24 horas"
  uptimeWeek: "tiempo de actividad 7 d칤as"
  uptimeMonth: "tiempo de actividad 30 d칤as"
  uptimeYear: "tiempo de actividad 1 a침o"
  liveStatus: "Estado en vivo"
  liveStatusHtmlComment: "<!--estado en vivo-->"
  allSystemsOperational: "游릴 Todos los sistemas operativos"
  degradedPerformance: "游릳 Rendimiento degradado"
  completeOutage: "游린 Sin servicio"
  parcialOutage: "游릲 Interrupci칩n parcial"