# Change these first
owner: imedicalservices # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:
  - name: AXA
    url: https://axacolpatria.imedicalcloud.net/api/v1/healthz?token=3a9174fb-6e18-41c7-a53d-6d1ddf871819

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /statuspage
  logoUrl: https://avatars.githubusercontent.com/u/107059814
  name: iMedical Estado de Servicios
  introTitle: "**iMedical** plataforma de servicios de salud."
  introMessage: Esta página muestra en **tiempo real** el estado de los servicios de iMedical.
  navbar:
    - title: Estado
      href: /statuspage
    - title: Más información
      href: https://www.imedicalservices.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
